name: Deploy cloud_function
on:
  push:
    branches:
      - master
    paths:
      - 'cloud_function/**'

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    env:
      REGION: us-central1
      ENTRY_POINT: hello_world
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.RUN_PROJECT }}
          service_account_email: ${{ secrets.EMAIL }}
          service_account_key: ${{ secrets.CF_SA_KEY }}
      - name: Deploy Functions
        run: |
          gcloud functions deploy sample_function --source ./cloud_function --region=${REGION} --entry-point ${ENTRY_POINT} --runtime python38